# Generated by Django 4.1 on 2022-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthTimeUsage',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('base_mm', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=2, null=True)),
                ('base_tm', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('usage_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'month_time_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthUsage',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('base_mm', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=7, null=True)),
                ('usage_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
            ],
            options={
                'db_table': 'month_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulUsage',
            fields=[
                ('base_tm', models.IntegerField(primary_key=True, serialize=False)),
                ('usage_amt', models.DecimalField(blank=True, decimal_places=4, max_digits=46, null=True)),
                ('life_popul', models.FloatField(blank=True, null=True)),
                ('bus_popul', models.FloatField(blank=True, null=True)),
                ('sub_popul', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'popul_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainUsage06',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('base_dt', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('usage_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
                ('rain_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_usage_06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationNear',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_addr', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('dong_cd', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('bus_cnt', models.BigIntegerField(blank=True, null=True)),
                ('culture_cnt', models.BigIntegerField(blank=True, null=True)),
                ('event_cnt', models.BigIntegerField(blank=True, null=True)),
                ('mall_cnt', models.BigIntegerField(blank=True, null=True)),
                ('park_cnt', models.BigIntegerField(blank=True, null=True)),
                ('road_cnt', models.BigIntegerField(blank=True, null=True)),
                ('school_cnt', models.BigIntegerField(blank=True, null=True)),
                ('sub_cnt', models.BigIntegerField(blank=True, null=True)),
                ('tour_cnt', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_near',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationUsage',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rent_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=41, null=True)),
                ('return_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=41, null=True)),
            ],
            options={
                'db_table': 'station_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeUsage',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('base_tm', models.TextField(blank=True, null=True)),
                ('usage_amt', models.DecimalField(blank=True, decimal_places=4, max_digits=46, null=True)),
            ],
            options={
                'db_table': 'time_usage',
                'managed': False,
            },
        ),
    ]
